Project/FlowerShop/Controllers/CartController.cs
using FlowerShop.ViewModels.ViewModelCart;
using FlowerShopLibrary.Models;
using FlowerShopLibrary.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlowerShop.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductService _iproductservice;
        private readonly IOrderService _iorderservice;
        private readonly IOrderDetailsService _iorderdetailservice;

        public CartController(IProductService iproductservice,
                              IOrderService iorderservice,
                              IOrderDetailsService iorderdetailservice)
        {
            _iproductservice = iproductservice;
            _iorderservice = iorderservice;
            _iorderdetailservice = iorderdetailservice;       
        }

        private int IsInCart(int id)
        {
           var cart = (List<ViewModelItem>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Products.Id == id)
                    return i;
            return -1;
        }

        public ActionResult Index()
        {

            return View();
        }
        // GET: Cart
        public ActionResult Buy(int id)
        {
            var getProductById = _iproductservice.GetProductById(id);
            if (Session["cart"] == null)
            {
               var cart = new List<ViewModelItem>();
                cart.Add(new ViewModelItem()
                {
                    Products = getProductById,
                    DiscountedPrice = getProductById.FlowerDiscount != null ? (getProductById.FlowerPrice - (getProductById.FlowerPrice / 100 * (decimal)getProductById.FlowerDiscount)) : 0,
                    Quantity = 1
                });
                Session["cart"] = cart;
            }
            else
            {
                var cart = (List<ViewModelItem>)Session["cart"];
               // var getProductById = _iproductservice.GetProductById(id);
                int index = IsInCart(id);
                if (index == -1)
                {
                    cart.Add(new ViewModelItem()
                    {
                        Products = getProductById,
                        DiscountedPrice = getProductById.FlowerDiscount != null ? (getProductById.FlowerPrice - (getProductById.FlowerPrice / 100 * (decimal)getProductById.FlowerDiscount)) : 0,
                        Quantity = 1
                    });
                }
                else
                {
                    cart[index].Quantity = cart[index].Quantity + 1;
                }
                Session["cart"] = cart;
            }

            return View("Index");
        }

        public ActionResult Delete(int id)
        {
            var cart = (List<ViewModelItem>)Session["cart"];
            cart.RemoveAt(id);
            Session["cart"] = cart;
            return View("Index");
        }

        public ActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Checkout(ViewModelOrder model)
        {
            var cart = (List<ViewModelItem>)Session["cart"];
            decimal total = 0;
            
            foreach(var value in cart)
            {
                total = total + (value.Quantity * (value.Products.FlowerDiscount != null ? (value.Products.FlowerPrice - (value.Products.FlowerPrice / 100 * (decimal)value.Products.FlowerDiscount)) : value.Products.FlowerPrice));
            }
            //Save Order
            Order order = new Order()
            {
                FirstName = model.ViewOrderFirstName,
                LastName = model.ViewOrderLastName,
                OrderAdress = model.ViewOrderAdress,
                OrderCity = model.ViewOrderCity,
                OrderPostalCode = model.ViewOrderPostalCode,
                OrderCountry = model.ViewOrderCountry,
                OrderPhone = model.ViewOrderPhone,
                OrderEmail = model.ViewOrderEmail,
                OrderDate = DateTime.UtcNow,
                OrderTotal = total   
            };
            int orderId = _iorderservice.Create(order);


            //Save Order Details
            foreach(var value in cart)
            {
                OrderDetails orderdetails = new OrderDetails()
                {
                    OrderId = orderId,
                    ProductId = value.Products.Id,
                    //UnitPrice = value.Products.FlowerPrice,
                    UnitPrice = value.Products.FlowerDiscount != null ? (value.Products.FlowerPrice - (value.Products.FlowerPrice / 100 * (decimal)value.Products.FlowerDiscount)) : value.Products.FlowerPrice,
                    //value.FlowerDiscount != null ? (value.FlowerPrice - (value.FlowerPrice / 100 * (decimal)value.FlowerDiscount)) : 0
                    Quantaty = value.Quantity
                };
                _iorderdetailservice.Create(orderdetails);
            }

            // remove cart
            Session.Remove("cart");

            return View("Thanks");
        }
    }
}

Project/FlowerShop/Controllers/ShopController.cs
using FlowerShop.Core;
using FlowerShop.Util;
using FlowerShop.ViewModels.ViewModelNews;
using FlowerShop.ViewModels.ViewModelShop;
using FlowerShopLibrary.Models;
using FlowerShopLibrary.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;


namespace FlowerShop.Controllers
{
    public class ShopController : Controller
    {
        private readonly IProductService _iproductservice;
        private readonly INewsService _inewsservice;
        private int PageSize = 4;

        public ShopController(IProductService iproductservice, INewsService inewsservice)
        {
            _iproductservice = iproductservice;
            _inewsservice = inewsservice;
        }

        public IQueryable<Product> SortProductList(IEnumerable<Field> sortOrder, IQueryable<Product> list)
        {
            if (sortOrder != null)
            {
                foreach (var field in sortOrder)
                {

                    if (!field.Sort)
                        continue;

                    switch (field.Name)
                    {
                        case "FlowerPrice":
                            if (field.SortDirection == SortDirection.Ascending)
                            {
                                list = list.OrderBy(c => c.FlowerPrice);
                            }
                            else
                                list = list.OrderByDescending(c => c.FlowerPrice);
                            break;
                    }
                }
            }
            return list;
        }
        // GET: Shop
        // [ClaimsAuthorize(MyRole = "User")]
        public ActionResult Index(int page = 1)
        {
            var model = new List<ViewModelShop>();

            var list = _iproductservice.GetProductsList().ToList();
            ViewBag.Categories = _iproductservice.GetCategory().ToList();

            foreach (var value in list)
            {
                model.Add(new ViewModelShop()
                {
                    Id = value.Id,
                    ProductName = value.FlowerName,
                    ProductDescription = value.FlowerDescription,
                    ProductImages = value.FlowerImages.ToList(),
                    ProductPrice = value.FlowerPrice,
                    ProductDiscount = value.FlowerDiscount.ToString(),
                    ProductPriceWithDiscount = Decimal.ToInt32(value.FlowerDiscount != null ? (value.FlowerPrice - (value.FlowerPrice / 100 * (decimal)value.FlowerDiscount)) : 0),
                    Special = value.Special
                });
            }

            PagedList<ViewModelShop> pmodel = new PagedList<ViewModelShop>(model, page, PageSize);

            return View(pmodel);
        }

        public ActionResult Browse()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var product = _iproductservice.GetProductById(id);

            var model = new ViewModelShopDetails()
            {
                DetailId = product.Id,
                DetailsName = product.FlowerName,
                DetailsDescription = product.FlowerDescription,
                DetailsImages = product.FlowerImages.ToList(),
                DetailsCategory = product.Category.ToString(),
                DetailsPrice = product.FlowerDiscount != null ? (product.FlowerPrice - (product.FlowerPrice / 100 * (decimal)product.FlowerDiscount)) : product.FlowerPrice
                //value.FlowerDiscount != null ? (value.FlowerPrice - (value.FlowerPrice / 100 * (decimal)value.FlowerDiscount)) : 0
            };

            return View(model);
        }

        public ActionResult AxajIndex(string searchCategory, TableParam tableParam, int page)
        {
            var list = _iproductservice.GetProductsList();
            var newList = new List<Product>();
            //ViewBag.Categories = _iproductservice.GetCategory().ToList();

            if (searchCategory != null)
            {
                list = _iproductservice.GetProductCategories(searchCategory);
            }

            foreach (var value in list)
            {
                newList.Add(new Product()
                {
                    Id = value.Id,
                    FlowerName = value.FlowerName,
                    FlowerDescription = value.FlowerDescription,
                    FlowerImages = value.FlowerImages,
                    FlowerDiscount = value.FlowerDiscount,
                    FlowerPrice = value.FlowerDiscount != null ? (value.FlowerPrice - (value.FlowerPrice / 100 * (decimal)value.FlowerDiscount)) : value.FlowerPrice,
                    Special = value.Special
                }
              );
            }

            IQueryable<Product> iquerableList = newList.AsQueryable();

            list = SortProductList(tableParam.Fields, iquerableList);

            var model = new List<ViewModelShop>();


            foreach (var value in list)
            {
                decimal flowerPrice = value.FlowerPrice;
                if (value.FlowerDiscount != null)
                {
                    flowerPrice = (value.FlowerPrice / (100 - (decimal)value.FlowerDiscount) * 100);
                }

                model.Add(new ViewModelShop()
                {
                    Id = value.Id,
                    ProductName = value.FlowerName,
                    ProductDescription = value.FlowerDescription,
                    ProductImages = value.FlowerImages.ToList(),
                    ProductDiscount = value.FlowerDiscount.ToString(),
                    ProductPrice = value.FlowerDiscount != null ? flowerPrice : value.FlowerPrice,
                    ProductPriceWithDiscount = Decimal.ToInt32(value.FlowerDiscount != null ? (flowerPrice - (flowerPrice / 100 * (decimal)value.FlowerDiscount)) : 0),
                    Special = value.Special
                });
            }

            //if (model.Count != 0)
            //{
                PagedList<ViewModelShop> pmodel = new PagedList<ViewModelShop>(model, page, PageSize);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("_Index", pmodel);
                }

                return View("Index", pmodel);
            //}
            //if (Request.IsAjaxRequest())
            //{
            //    return PartialView("_Index");
            //}
            //return View("Index");
        }

        public PartialViewResult SideSlideShow()
        {
            var list = _iproductservice.GetProductsList();
            var model = new List<ViewModelShop>();

            foreach (var value in list)
            {
                model.Add(new ViewModelShop()
                {
                    Id = value.Id,
                    ProductName = value.FlowerName,
                    ProductPrice = value.FlowerPrice,
                    ProductImages = value.FlowerImages.ToList()
                });
            }

            return PartialView("_SideSlideShow", model);
        }

        public ActionResult ProductSearch(string search)
        {
            var list = _iproductservice.GetProductsList();
            var model = new List<ViewModelShop>();

            if (search != null)
            {
                list = _iproductservice.SearchList(list, search);
            }

            foreach (var value in list)
            {
                decimal flowerPrice = value.FlowerPrice;
                if (value.FlowerDiscount != null)
                {
                    flowerPrice = (value.FlowerPrice / (100 - (decimal)value.FlowerDiscount) * 100);
                }

                model.Add(new ViewModelShop()
                {
                    Id = value.Id,
                    ProductName = value.FlowerName,
                    ProductDescription = value.FlowerDescription,
                    ProductImages = value.FlowerImages.ToList(),
                    ProductDiscount = value.FlowerDiscount.ToString(),
                    ProductPrice = value.FlowerPrice,
                    ProductPriceWithDiscount = Decimal.ToInt32(value.FlowerDiscount != null ? (flowerPrice - (flowerPrice / 100 * (decimal)value.FlowerDiscount)) : 0),
                    Special = value.Special
                }
              );
            }

            return View("Search", model);

        }

        //News Carousele

        public PartialViewResult NewsCarousel()
        {
            var list = _inewsservice.GetNewsList().ToList();
            var model = new List<ViewModelNews>();

            foreach (var value in list)
            {
                model.Add(new ViewModelNews()
                {
                    ViewId = value.Id,
                    ViewTitle = value.Title,
                    ViewDescription = value.Description,
                    ViewImage = value.Image
                });
            }

            return PartialView("_NewsCarousel", model);
        }

        //Category
        public ActionResult Category(string categoryName, TableParam tableParam, int page = 1)
        {
            var model = new List<ViewModelShop>();

            var list = _iproductservice.GetProductCategories(categoryName);
            //ViewBag.Categories = _iproductservice.GetCategory().ToList();


            list = SortProductList(tableParam.Fields, list);

            foreach (var value in list)
            {
                model.Add(new ViewModelShop()
                {
                    Id = value.Id,
                    ProductName = value.FlowerName,
                    ProductDescription = value.FlowerDescription,
                    ProductImages = value.FlowerImages.ToList(),
                    ProductPrice = value.FlowerPrice,
                    ProductDiscount = value.FlowerDiscount.ToString(),
                    ProductCategory = value.Category.CategoryName,

Project/FlowerShop/Views/Cart/Buy.cshtml
@*@model List<FlowerShop.ViewModels.ViewModelCart.ViewModelItem>
@{
    ViewBag.Title = "Buy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Buy</h2>

<table>
    <tr>
        <th>@Html.LabelFor(i => i.FirstOrDefault().Products.FlowerName)</th>
        <th>@Html.LabelFor(i => i.FirstOrDefault().Products.FlowerPrice)</th>
        <th>@Html.LabelFor(i => i.FirstOrDefault().Quantity)</th>
    </tr>
    @foreach(var value in Model)
    {
        <tr>
            <td>@value.Products.FlowerName</td>
            <td>@value.Products.FlowerPrice</td>
            <td>@value.Quantity</td>
        </tr>
    }
    <tr>
        <td>
            <a href="#">CheckOut</a>
        </td>
    </tr>
</table>*@

Project/FlowerShop/Views/Cart/Checkout.cshtml
@model FlowerShop.ViewModels.ViewModelCart.ViewModelOrder
@using System.Web.Optimization
@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section javascriptsmain {
    @Styles.Render("~/bundles/cart-main.css")
}

@using (Html.BeginForm("Checkout", "Cart", FormMethod.Post)){
<div class="row">
    <div class="checkout-box-values col-md-offset-2 col-md-8">
        <h2>Checkout</h2>
        <div class="row">
            <div class="checkout-box col-md-12">
                <div class="col-md-offset-3 col-md-3">@Html.LabelFor(c => c.ViewOrderFirstName)</div>
                <div class="col-md-6">@Html.TextBoxFor(c => c.ViewOrderFirstName)</div>
            </div>
            <div class="checkout-box col-md-12">
                <div class="col-md-offset-3 col-md-3">@Html.LabelFor(c => c.ViewOrderLastName)</div>
                <div class="col-md-6">@Html.TextBoxFor(c => c.ViewOrderLastName)</div>
            </div>
            <div class="checkout-box col-md-12">
                <div class="col-md-offset-3 col-md-3">@Html.LabelFor(c => c.ViewOrderAdress)</div>
                <div class="col-md-6">@Html.TextBoxFor(c => c.ViewOrderAdress)</div>
            </div>
            <div class="checkout-box col-md-12">
                <div class="col-md-offset-3 col-md-3">@Html.LabelFor(c => c.ViewOrderCity)</div>
                <div class="col-md-6">@Html.TextBoxFor(c => c.ViewOrderCity)</div>
            </div>
            <div class="checkout-box col-md-12">
                <div class="col-md-offset-3 col-md-3">@Html.LabelFor(c => c.ViewOrderPostalCode)</div>
                <div class="col-md-6">@Html.TextBoxFor(c => c.ViewOrderPostalCode)</div>
            </div>
            <div class="checkout-box col-md-12">
                <div class="col-md-offset-3 col-md-3">@Html.LabelFor(c => c.ViewOrderCountry)</div>
                <div class="col-md-6">@Html.TextBoxFor(c => c.ViewOrderCountry)</div>
            </div>
            <div class="checkout-box col-md-12">
                <div class="col-md-offset-3 col-md-3">@Html.LabelFor(c => c.ViewOrderPhone)</div>
                <div class="col-md-6">@Html.TextBoxFor(c => c.ViewOrderPhone)</div>
            </div>
            <div class="checkout-box col-md-12">
                <div class="col-md-offset-3 col-md-3">@Html.LabelFor(c => c.ViewOrderEmail)</div>
                <div class="col-md-6">@Html.TextBoxFor(c => c.ViewOrderEmail)</div>
            </div>
        </div>
        <div class="row">
            <div class="checkbox">
                <input type="submit" value="Submit" class="btn btn btn-default" />
            </div>
        </div>
    </div>
</div>
}

Project/FlowerShop/Views/Cart/Index.cshtml
@model List<FlowerShop.ViewModels.ViewModelCart.ViewModelItem>
@using FlowerShop.ViewModels.ViewModelCart
@using System.Web.Optimization
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section javascriptsmain {
    @Styles.Render("~/bundles/cart-main.css")   
}


@{
    var cart = (List<ViewModelItem>)Session["cart"];
    int cartId = 0;
    string sum = "";
}
<div class="row">
    <div class="cart-box col-md-12">
        <div class="col-md-offset-2 col-md-8 cart-box-table">
            <h2>Cart</h2>
            <table class="table table-hover table-responsive">
                <tr>
                    <th>@Html.LabelFor(i => i.FirstOrDefault().Products.FlowerName)</th>
                    <th class="hide-table-field">@Html.LabelFor(i => i.FirstOrDefault().Products.FlowerPrice)</th>
                    <th>@Html.LabelFor(i => i.FirstOrDefault().Quantity)</th>
                    <th>Q x Price</th>
                    <th class="hide-table-field">Details</th>
                    <th>Remove</th>
                </tr>
                @if (cart != null)
            {
                foreach (var value in cart)
                {
                        <tr>
                            <td>@value.Products.FlowerName</td>
                            @if (value.DiscountedPrice != 0)
                    {
                                <td class="hide-table-field">@value.DiscountedPrice</td>
                                <td>@value.Quantity</td>
                                <td>@(value.DiscountedPrice * value.Quantity)$</td>
                            }
                            else
                            {
                                <td class="hide-table-field">@value.Products.FlowerPrice</td>
                                <td>@value.Quantity</td>
                                <td>@(string.Format("{0:0.00}", (value.Products.FlowerPrice * value.Quantity)))$</td>
                            }
                            <td class="hide-table-field"><a href="@Url.Action("Details", "Shop", new { id = value.Products.Id })">Details</a></td>
                            <td><a href="@Url.Action("Delete", "Cart", new { id = cartId })">Remove</a></td>
                        </tr>
                        cartId++;

                    }
                    {
                        var cartSum = (List<ViewModelItem>)Session["cart"];

                        sum = string.Format("{0:0.00}", cartSum.Sum(i => i.DiscountedPrice != 0 ? i.Quantity * i.DiscountedPrice : i.Quantity * i.Products.FlowerPrice));
                    }

                }
            </table>
        </div>
        <div class="col-md-offset-2 col-md-8 cart-box-action">
            <div class="car-box-sum col-md-12">
                <h2>Total Price: @sum $</h2>
            </div>

            <div class="car-box-checkout col-md-12">
                <div class="checkout-button">
                    <a href="@Url.Action("Checkout", "Cart")">
                        Checkout
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

Project/FlowerShop/Views/Cart/Thanks.cshtml
@{
    ViewBag.Title = "Thanks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thanks</h2>

<p>Thanks for purchase! Please click <a href="@Url.Action("Index", "Shop")">here</a> to continue.</p>