Project/FlowerShop/Controllers/NavigationController.cs
using FlowerShop.ViewModels.ViewModelNavigation;
using FlowerShopLibrary.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlowerShop.Controllers
{
    public class NavigationController : Controller
    {
        private readonly INavigationService _inavigationservice;

        public NavigationController(INavigationService inavigationservice)
        {
            _inavigationservice = inavigationservice;
        }
        // GET: Navigation

        public PartialViewResult Menu()
        {
            var model = _inavigationservice.GetListNav();

            return PartialView("_CategoryMenu", model);
        }


        public PartialViewResult LastProductContent()
        {
            var model = new List<ViewModelNavigation>();
            var list = _inavigationservice.LastProduct(3).ToList();

            foreach(var value in list)
            {
                model.Add(new ViewModelNavigation()
                {
                    Id = value.Id,
                    LastProductName = value.FlowerName
                });
            }

            return PartialView("_LastProductContent" , model);

        }
    }
}

Project/FlowerShop/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    
    @Scripts.Render("~/bundles/main-scripts")
    @Styles.Render("~/bundles/main-styles")
    @RenderSection("javascriptsmain", required: false)

    <title>@ViewBag.Title</title>
</head>
<body>
    @*@Html.Partial("_LoadSpiner")*@
    <div class="Body">     
            @*<div class="row register">
                <div class="col-md-offset-1 col-md-9 col-sm-10">@Html.Partial("_LoginPartial")</div>
            </div>*@
            @*<div class="row menu">*@
                @Html.Partial("Page/_PageNavigation")
            @*</div>*@
        <div class="container main-box">
            @*<div class="row">*@
                @*<div class="col-md-offset-1 col-md-11 col-sm-12">*@
                    @RenderBody()    
                @*</div>*@
                @*<div class="sm-hidden">
                    Hello world!
                </div>*@
            @*</div>*@
        </div>
            <footer>
                <div class="row foot">
                    <div class="col-md-12">
                        @Html.Partial("Page/_PageFooter")
                    </div>
                </div>
            </footer>
        </div> 
    @Html.Partial("_Modal")
</body>
</html>

Project/FlowerShop/Views/Shared/_LayoutAdmin.cshtml
@using System.Web.Optimization
<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    @Scripts.Render("~/bundles/main-scripts")
    @Styles.Render("~/bundles/main-styles")
    @RenderSection("javascriptsmainadmin", required: false)

    <title>@ViewBag.Title</title>
</head>
<body>
    @Html.Partial("_LoadSpiner")
    <div class="Body">
        <div class="row menu">
            @Html.Partial("Page/_PageNavigation")
        </div>
        <div class="container container-body">          
            <div class="row">
               
                <div class="col-md-9 body-content">
                    @RenderBody()
                </div>
                <div class="col-md-2 side-navigation">
                    <h2>Manage</h2>
                    <div class="row">
                        <a href="@Url.Action("List", "Product")">Product</a>
                        @{Html.RenderAction("Menu", "Navigation");}
                    </div>
                    <div class="row">
                        <a href="@Url.Action("List", "Category")">Category</a>
                    </div>
                    <div class="row">
                        <a href="@Url.Action("List", "News")">News</a>
                    </div>
                    
                </div>
                @*<div class="sm-hidden">
                    Hello world!
                </div>*@
            </div>
            
        </div>
        <footer>
            <div class="row foot">
                <div class="col-md-12">
                    @Html.Partial("Page/_PageFooter")
                </div>
            </div>
        </footer>
    </div>
    @Html.Partial("_Modal")
</body>
</html>

Project/FlowerShop/Views/Shared/_LayoutHome.cshtml
@using System.Web.Optimization
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Scripts.Render("~/bundles/main-scripts")
    @*@Styles.Render("~/bundles/main-styles")*@

    @RenderSection("javascriptshome", required: false)
    <title>@ViewBag.Title</title>
</head>
<body>
    @Html.Partial("_LoadSpiner")
    <div class="body">
        <div class="home-navigation">
            @Html.Partial("Page/_PageNavigation")
        </div>


        <div>
            @RenderBody()
        </div>
        @Html.Partial("_Modal")
    </div>
</body>
</html>

Project/FlowerShop/Views/Shared/_LoadSpiner.cshtml
<div class="overlay">
    <div class="spiner spiner-1"></div>
</div>

Project/FlowerShop/Views/Shared/_Modal.cshtml
<div class="modal fade" id="myModal" role="dialog">
    <div class="row">
        <div class="modal-size">
            <div class="modal-dialog">
                <div class="modal-content">

                </div>
            </div>
        </div>
    </div>
</div>